# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrt_regression <- function(ww, X1, Y, groupLen, rangeGroupInd, lambda2, lambda1, nlambda, d, kG, num_relaxation_round, max_iter, innerIter, standard) {
    .Call(`_MultiNet_sqrt_regression`, ww, X1, Y, groupLen, rangeGroupInd, lambda2, lambda1, nlambda, d, kG, num_relaxation_round, max_iter, innerIter, standard)
}

nodewise <- function(data, K, nrow, p, num_relaxation_round, residual, max_iter, innerIter, tmp, index, lambda1, lambda2, nlam, groupLen, rangeGroupInd, beta, f, tau, standard, cc) {
    .Call(`_MultiNet_nodewise`, data, K, nrow, p, num_relaxation_round, residual, max_iter, innerIter, tmp, index, lambda1, lambda2, nlam, groupLen, rangeGroupInd, beta, f, tau, standard, cc)
}

